import { StyleSheet, Dimensions } from 'react-native';

const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f0f0f0',
        padding: 20,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
    },
    headerText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#003300',
        marginBottom: 20,
    },
    headerIcons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '20%',
    },
    iconButton: {
        padding: 5,
    },
    inputContainer: {
        marginBottom: 15,
        width: '100%',
    },
    label: {
        fontSize: 16,
        color: '#003300',
        marginBottom: 5,
    },
    input: {
        height: 40,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5,
        paddingHorizontal: 10,
        backgroundColor: '#fff',
        width: '90%',
        marginBottom: 10,
    },
    multilineInput: {
        height: 100,
    },
    button: {
        backgroundColor: '#006400',
        padding: 15,
        borderRadius: 5,
        marginVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 3,
    },
    fullWidthButton: {
        width: '100%',
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        marginLeft: 10,
    },
    errorText: {
        color: 'red',
        marginTop: 10,
        textAlign: 'center',
    },
    notificationList: {
        marginTop: 20,
        width: '100%',
    },
    listHeader: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    notificationItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    notificationText: {
        fontSize: 16,
    },
    incidentCard: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        marginBottom: 20,
        alignItems: 'flex-start',
        elevation: 3,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        width: '100%',
    },
    incidentText: {
        fontSize: 16,
        marginBottom: 5,
        color: '#003300',
    },
    buttonContainer: {
        flexDirection: 'column',
        width: '100%',
    },
    assignButton: {
        backgroundColor: '#006400',
        padding: 10,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
    },
    updateButton: {
        backgroundColor: '#007BFF',
        padding: 10,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
    },
    deleteButton: {
        backgroundColor: '#DC3545',
        padding: 10,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        marginBottom: 20,
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        width: '45%',
    },
    cardTitle: {
        fontSize: 18,
        color: '#003300',
        fontWeight: 'bold',
        marginTop: 10,
    },
    cardValue: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#006400',
        textAlign: 'center',
        marginTop: 10,
    },
    cardContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginVertical: 10,
    },
    mapContainer: {
        height: 300,
        marginBottom: 20,
        width: '100%',
    },
    map: {
        flex: 1,
        width: screenWidth - 20,
        borderRadius: 10,
    },
    formCard: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        marginBottom: 20,
        width: '90%',
    },
    statusCard: {
        backgroundColor: '#e3f2fd',
        borderRadius: 8,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        marginBottom: 20,
        width: '90%',
    },
    cardContent: {
        padding: 8,
    },
    statusText: {
        fontSize: 16,
        marginVertical: 4,
    },
    boldText: {
        fontWeight: 'bold',
    },
    homeButton: {
        backgroundColor: '#006400',
        padding: 15,
        borderRadius: 8,
        marginVertical: 10,
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 3,
    },
    homeButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    iconStyle: {
        marginRight: 10,
    },
    nonClickableCard: {
        width: '48%',
        backgroundColor: '#e0e0e0',
        borderRadius: 10,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 1,
        alignItems: 'center',
    },
    contactCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 16,
        marginBottom: 15,
        elevation: 3,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        width: '100%',
    },
    contactIcon: {
        marginRight: 15,
    },
    contactInfo: {
        flex: 1,
    },
    contactName: {
        fontSize: 18,
        fontWeight: '600',
        color: '#003300',
    },
    callButton: {
        backgroundColor: '#006400',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 5,
        marginTop: 5,
        alignItems: 'center',
    },
    callButtonText: {
        color: '#fff',
        fontSize: 16,
    },
    helpSection: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
        marginBottom: 10,
        width: '100%',
    },
    helpQuestion: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#003300',
        flex: 1,
    },
    helpAnswer: {
        fontSize: 14,
        color: '#555',
    },
    icon: {
        marginRight: 10,
    },
    logo: {
        width: 258,
        height: 257,
        resizeMode: 'contain',
        marginBottom: 20,
        alignSelf: 'center',
    },
    disabledButton: {
        backgroundColor: '#ccc',
        opacity: 0.6,
    },
});
